// Fit film params so that iPhone photos pushed through makeFilm() match the colour statistics of
// real photos shot on each stock. Usage: node calibration/fit.mjs [filmId ...]
// Writes calibration/fitted.json and regenerates js/films-calibrated.js.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { makeFilm, srgbToLinear, FIT_SPEC, FIT_SPEC_BW, paramVector, applyVector, specBounds } from '../js/film-transform.js';
import { FILMS } from '../js/films.js';
import { loadPool, poolStats, statDistance } from './stats.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const M = join(HERE, 'cache', 'measure');
const FIT_PIXELS = 16000;
const PRIOR = 0.004;     // pull toward the hand-authored params (per normalised param²)

const base = loadPool(join(M, 'baseline', 'pool.bin'), FIT_PIXELS);
if (!base) throw new Error('run measure.py first (no baseline pool)');
const baseLin = base.map(srgbToLinear);
const baseStats = poolStats(base);

function render(params) {
  const fn = makeFilm(params), out = new Float32Array(baseLin.length), o = [0, 0, 0];
  for (let i = 0; i < baseLin.length; i += 3) {
    fn(baseLin[i], baseLin[i + 1], baseLin[i + 2], o);
    out[i] = o[0]; out[i + 1] = o[1]; out[i + 2] = o[2];
  }
  return out;
}

function fitFilm(film, target) {
  const bw = film.params.type === 'bw';
  const spec = bw ? FIT_SPEC_BW : FIT_SPEC;
  const prior = { ...film.params, ...(bw ? {} : { lumaLock: true }) };
  const { lo: min, hi: max } = specBounds(spec);
  const x0 = paramVector(spec, prior);
  const range = Array.from(min, (m, i) => max[i] - m || 1);
  const loss = (x) => {
    let reg = 0;
    for (let i = 0; i < x.length; i++) reg += ((x[i] - x0[i]) / range[i]) ** 2;
    return statDistance(poolStats(render(applyVector(spec, x, prior))), target, { bw }) + PRIOR * reg;
  };
  // Coordinate pattern search with shrinking steps — robust for a noisy, bounded, mildly coupled objective.
  let x = Float64Array.from(x0), best = loss(x);
  const start = best;
  for (let step = 0.25; step > 0.01; step *= 0.5) {
    for (let sweep = 0, improved = true; sweep < 3 && improved; sweep++) {
      improved = false;
      for (let i = 0; i < x.length; i++) {
        for (const dir of [1, -1]) {
          const v = Math.min(max[i], Math.max(min[i], x[i] + dir * step * range[i]));
          if (v === x[i]) continue;
          const old = x[i]; x[i] = v;
          const l = loss(x);
          if (l < best) { best = l; improved = true; break; }
          x[i] = old;
        }
      }
    }
  }
  const params = applyVector(spec, x, prior);
  return { params, start, best, identity: statDistance(baseStats, target, { bw }) };
}

const only = process.argv.slice(2);
const fittedPath = join(HERE, 'fitted.json');
const fitted = existsSync(fittedPath) ? JSON.parse(readFileSync(fittedPath, 'utf8')) : {};
for (const film of FILMS) {
  if (only.length && !only.includes(film.id)) continue;
  const poolPath = join(M, 'films', film.id, 'pool.bin');
  const statsPath = join(M, 'films', film.id, 'stats.json');
  if (!existsSync(poolPath)) continue;
  const meta = JSON.parse(readFileSync(statsPath, 'utf8'));
  if (meta.images < 8) { console.log(film.id, 'skipped: only', meta.images, 'usable images'); continue; }
  const target = poolStats(loadPool(poolPath, 40000));
  const t0 = Date.now();
  const r = fitFilm(film, target);
  fitted[film.id] = { images: meta.images, grain: meta.grain, loss: { identity: r.identity, handTuned: r.start, fitted: r.best }, params: r.params };
  console.log(`${film.id.padEnd(32)} imgs ${String(meta.images).padStart(3)}  identity ${r.identity.toFixed(4)}  hand ${r.start.toFixed(4)}  fit ${r.best.toFixed(4)}  ${((Date.now() - t0) / 1000).toFixed(0)}s`);
  writeFileSync(fittedPath, JSON.stringify(fitted, null, 1));
}

// Generated module consumed by js/films.js: only the colour params (spatial ones stay hand-authored).
const SPATIAL = new Set(['grain', 'halation', 'bloom']);
const out = Object.fromEntries(Object.entries(fitted).map(([id, f]) => [id, {
  images: f.images,
  params: Object.fromEntries(Object.entries(f.params).filter(([k]) => !SPATIAL.has(k))),
}]));
writeFileSync(join(HERE, '..', 'js', 'films-calibrated.js'),
  `// GENERATED by calibration/fit.mjs — do not edit by hand.\n` +
  `// Colour params fitted to statistics of real photos shot on each stock (Wikimedia Commons samples)\n` +
  `// relative to an iPhone baseline. films.js merges these over the hand-authored params.\n` +
  `export const CALIBRATED = ${JSON.stringify(out)};\n`);
