// C41 — film-stock inventory. Data only (plus getFilm). See docs/ARCHITECTURE.md §2.
// Parameters are interpreted by js/film-transform.js (FILM_DEFAULTS schema).
// docs/FILM_STOCKS.md is generated from this file: `npm run docs:films`.

export const FILM_CATEGORIES = [
  { id: 'color', label: 'Colour' },
  { id: 'bw', label: 'B&W' },
  { id: 'slide', label: 'Slide' },
  { id: 'cine', label: 'Cinema' },
  { id: 'special', label: 'Specialty' },
];

const NEUTRAL_HALO = [1, 0.97, 0.94];
const bwHalo = (amount = 0.04) => ({ amount, color: NEUTRAL_HALO });
const redHalo = (amount = 0.07) => ({ amount, color: [1, 0.35, 0.15] });

export const FILMS = [
  // ───────────────────────────── Colour negative ─────────────────────────────
  {
    id: 'kodak-portra-400', name: 'Portra 400', brand: 'Kodak', iso: 400,
    category: 'color', process: 'C-41', status: 'current',
    swatch: ['#f2c14e', '#d9480f'],
    summary: 'The wedding & portrait standard: soft, warm skin and enormous latitude.',
    traits: {
      color: 'Natural, gently warm palette tuned for skin; muted, slightly olive greens and restrained blues.',
      contrast: 'Low, smooth tonal scale that flatters faces.',
      grain: 'Fine for ISO 400 (T-Grain), only visible in underexposed shadows.',
      highlights: 'Huge overexposure latitude; highlights roll off softly instead of clipping.',
      shadows: 'Open, slightly lifted shadows with a faint cool cast in the blacks.',
    },
    params: {
      temp: 0.04, contrast: -0.15, rolloff: 0.5, shadows: 0.15,
      lift: [0.01, 0.015, 0.03], sat: 0.92,
      hsl: { orange: [2, 1.05, 0.03], yellow: [-4, 0.9, 0], green: [-10, 0.75, -0.02], blue: [-3, 0.9, 0] },
      grain: { amount: 0.22, size: 1, color: 0.35 }, halation: redHalo(0.06),
    },
  },
  {
    id: 'kodak-portra-160', name: 'Portra 160', brand: 'Kodak', iso: 160,
    category: 'color', process: 'C-41', status: 'current',
    swatch: ['#f3ead7', '#c8963e'],
    summary: 'The quietest Portra: pastel, low-contrast and very fine-grained.',
    traits: {
      color: 'Neutral-to-warm, slightly pastel colour with natural skin and subdued greens.',
      contrast: 'The lowest contrast of the Portra family.',
      grain: 'Very fine; practically grainless in 35mm at box speed.',
      highlights: 'Very gentle shoulder, loves overexposure.',
      shadows: 'Soft and open, with a little cool lift.',
    },
    params: {
      temp: 0.02, contrast: -0.2, rolloff: 0.55, shadows: 0.12,
      lift: [0.01, 0.015, 0.025], sat: 0.85,
      hsl: { orange: [2, 1.02, 0.03], green: [-8, 0.75, 0], blue: [-2, 0.88, 0.01] },
      grain: { amount: 0.15, size: 0.68, color: 0.3 }, halation: redHalo(0.05),
    },
  },
  {
    id: 'kodak-portra-800', name: 'Portra 800', brand: 'Kodak', iso: 800,
    category: 'color', process: 'C-41', status: 'current',
    swatch: ['#f2c14e', '#7b2d8b'],
    summary: 'Fast Portra with warmer, richer colour and more bite than its siblings.',
    traits: {
      color: 'Warmer and more saturated than Portra 400; golden skin and richer reds.',
      contrast: 'Moderate — a touch punchier than 160/400.',
      grain: 'Visible but tight; noticeably finer than other ISO 800 stocks.',
      highlights: 'Smooth shoulder; holds tungsten and mixed light well.',
      shadows: 'Slightly cool, can go muddy if underexposed.',
    },
    params: {
      temp: 0.06, contrast: -0.06, rolloff: 0.45, shadows: 0.1,
      lift: [0.01, 0.02, 0.04], sat: 1.0,
      hsl: { red: [0, 1.08, 0], orange: [2, 1.08, 0.02], green: [-8, 0.8, -0.02] },
      grain: { amount: 0.38, size: 1.2, color: 0.4 }, halation: redHalo(0.08),
    },
  },
  {
    id: 'kodak-ektar-100', name: 'Ektar 100', brand: 'Kodak', iso: 100,
    category: 'color', process: 'C-41', status: 'current',
    swatch: ['#f6b917', '#c1121f'],
    summary: "Kodak's 'world's finest grain' negative: vivid, punchy, slide-like.",
    traits: {
      color: 'Highly saturated; punchy reds, deep blues and vivid greens. Skin can turn red-orange.',
      contrast: 'High for a negative film, close to slide.',
      grain: 'Extremely fine — the finest-grained colour negative available.',
      highlights: 'Less latitude than Portra; highlights hold but with a firmer shoulder.',
      shadows: 'Deep, clean blacks.',
    },
    params: {
      temp: 0.02, contrast: 0.25, rolloff: 0.3, sat: 1.28, vibrance: 0.1,
      hsl: { red: [0, 1.15, 0], orange: [-3, 1.1, 0], blue: [-2, 1.2, -0.04], green: [0, 1.05, 0] },
      grain: { amount: 0.08, size: 0.6, color: 0.3 }, halation: redHalo(0.05),
    },
  },
  {
    id: 'kodak-gold-200', name: 'Gold 200', brand: 'Kodak', iso: 200,
    category: 'color', process: 'C-41', status: 'current',
    swatch: ['#f6b917', '#e85d04'],
    summary: 'Consumer classic with golden, sunny warmth.',
    traits: {
      color: 'Distinct golden-yellow warmth, saturated yellows and oranges, nostalgic summer tones.',
      contrast: 'Moderate.',
      grain: 'Fine-to-moderate, more visible than pro stocks.',
      highlights: 'Highlights lean yellow; decent overexposure latitude.',
      shadows: 'Warm, slightly dense shadows.',
    },
    params: {
      temp: 0.09, contrast: 0.1, rolloff: 0.35, sat: 1.1,
      gain: [1.02, 1.01, 0.94], lift: [0.01, 0.005, 0],
      hsl: { yellow: [0, 1.15, 0.02], orange: [0, 1.1, 0], green: [-6, 0.92, 0] },
      grain: { amount: 0.3, size: 0.8, color: 0.4 }, halation: redHalo(0.07),
    },
  },
  {
    id: 'kodak-ultramax-400', name: 'UltraMax 400', brand: 'Kodak', iso: 400,
    category: 'color', process: 'C-41', status: 'current',
    swatch: ['#f6b917', '#1d4e89'],
    summary: 'All-round consumer 400: warm, saturated and forgiving.',
    traits: {
      color: 'Warm and saturated with strong reds and yellow-leaning greens.',
      contrast: 'Medium-high; punchy prints.',
      grain: 'Noticeable but pleasant.',
      highlights: 'Warm, moderately soft shoulder.',
      shadows: 'Fairly dense, slightly warm.',
    },
    params: {
      temp: 0.08, contrast: 0.15, rolloff: 0.35, sat: 1.15,
      gain: [1.02, 1.0, 0.95],
      hsl: { red: [0, 1.1, 0], yellow: [-2, 1.08, 0], green: [-6, 0.95, 0] },
      grain: { amount: 0.38, size: 1, color: 0.45 }, halation: redHalo(0.08),
    },
  },
  {
    id: 'kodak-colorplus-200', name: 'ColorPlus 200', brand: 'Kodak', iso: 200,
    category: 'color', process: 'C-41', status: 'current',
    swatch: ['#f6b917', '#2b9348'],
    summary: 'Budget Kodak with a soft, warm, nostalgic look.',
    traits: {
      color: 'Warm with yellow-orange bias; colours a little muted and vintage.',
      contrast: 'Low-to-moderate.',
      grain: 'Moderate, visible in skies.',
      highlights: 'Warm; less latitude than Gold.',
      shadows: 'Slightly lifted and soft.',
    },
    params: {
      temp: 0.1, contrast: 0.03, rolloff: 0.35, fade: 0.015, sat: 0.98,
      gain: [1.02, 1.0, 0.94],
      hsl: { yellow: [0, 1.08, 0], orange: [0, 1.05, 0.01], blue: [0, 0.9, 0], green: [-6, 0.88, 0] },
      grain: { amount: 0.35, size: 0.85, color: 0.45 }, halation: redHalo(0.07),
    },
  },
  {
    id: 'kodak-pro-image-100', name: 'Pro Image 100', brand: 'Kodak', iso: 100,
    category: 'color', process: 'C-41', status: 'current',
    swatch: ['#f6b917', '#6a994e'],
    summary: 'Portrait film for hot climates: warm, natural skin, fine grain.',
    traits: {
      color: 'Natural with mild warmth; pleasing skin and moderately saturated greens.',
      contrast: 'Moderate.',
      grain: 'Fine.',
      highlights: 'Good latitude, warm-neutral.',
      shadows: 'Clean and neutral.',
    },
    params: {
      temp: 0.06, contrast: 0.05, rolloff: 0.4, sat: 1.05,
      hsl: { orange: [1, 1.04, 0.02], green: [-4, 0.95, 0] },
      grain: { amount: 0.18, size: 0.6, color: 0.35 }, halation: redHalo(0.06),
    },
  },
  {
    id: 'fuji-superia-xtra-400', name: 'Superia X-TRA 400', brand: 'Fujifilm', iso: 400,
    category: 'color', process: 'C-41', status: 'current',
    swatch: ['#2b9348', '#0b6e4f'],
    summary: 'The Fuji consumer look: cool, green-leaning, vivid foliage.',
    traits: {
      color: 'Cooler than Kodak; strong, slightly cyan greens and clean blues. Fuji 4th colour layer keeps fluorescent light neutral.',
      contrast: 'Medium-high.',
      grain: 'Moderate, slightly crunchy.',
      highlights: 'Neutral to slightly cool.',
      shadows: 'Characteristic green/cyan tint in the shadows.',
    },
    params: {
      temp: -0.02, tint: -0.03, contrast: 0.15, rolloff: 0.35, sat: 1.1,
      lift: [0, 0.015, 0.012],
      hsl: { green: [6, 1.2, 0], aqua: [0, 1.05, 0], red: [0, 1.05, 0], orange: [-2, 0.95, 0] },
      splitShadow: { hue: 170, amt: 0.04 },
      grain: { amount: 0.4, size: 1, color: 0.45 }, halation: redHalo(0.07),
    },
  },
  {
    id: 'fuji-c200', name: 'Fujicolor C200', brand: 'Fujifilm', iso: 200,
    category: 'color', process: 'C-41', status: 'discontinued',
    swatch: ['#2b9348', '#e63946'],
    summary: 'Cheap and cheerful Fuji: cool-neutral with crisp greens.',
    traits: {
      color: 'Neutral-cool with clean greens and blues; slightly green bias.',
      contrast: 'Moderate.',
      grain: 'Fine-to-moderate.',
      highlights: 'Can go a little cool/cyan when overexposed.',
      shadows: 'Slightly green-cyan.',
    },
    params: {
      temp: -0.02, tint: -0.04, contrast: 0.08, rolloff: 0.35, sat: 1.0,
      lift: [0, 0.015, 0.015],
      hsl: { green: [4, 1.1, 0], blue: [0, 1.05, 0] },
      grain: { amount: 0.33, size: 0.8, color: 0.4 }, halation: redHalo(0.07),
    },
  },
  {
    id: 'fuji-pro-400h', name: 'Pro 400H', brand: 'Fujifilm', iso: 400,
    category: 'color', process: 'C-41', status: 'discontinued',
    swatch: ['#9ad1d4', '#3a5a40'],
    summary: 'Airy wedding film: pastel tones and signature minty greens.',
    traits: {
      color: 'Pastel, cool-leaning palette with mint/teal greens and soft, slightly pink skin.',
      contrast: 'Low; usually overexposed for a bright, airy look.',
      grain: 'Fine for 400.',
      highlights: 'Soft, creamy and bright.',
      shadows: 'Open, faintly cyan.',
    },
    params: {
      exposure: 0.25, temp: -0.02, contrast: -0.15, rolloff: 0.55, shadows: 0.1, sat: 0.85,
      lift: [0, 0.015, 0.02],
      hsl: { green: [14, 0.8, 0.04], aqua: [0, 0.9, 0.03], blue: [-6, 0.85, 0.02], orange: [-2, 0.95, 0.02] },
      grain: { amount: 0.22, size: 1, color: 0.35 }, halation: redHalo(0.06),
    },
  },
  {
    id: 'fuji-pro-160ns', name: 'Pro 160NS', brand: 'Fujifilm', iso: 160,
    category: 'color', process: 'C-41', status: 'discontinued',
    swatch: ['#a8dadc', '#1d3557'],
    summary: 'Soft, cool-neutral studio film with gentle greens.',
    traits: {
      color: 'Neutral to cool, low saturation, soft green-blue bias, natural skin.',
      contrast: 'Low.',
      grain: 'Very fine.',
      highlights: 'Smooth, slightly cool.',
      shadows: 'Open and neutral-cyan.',
    },
    params: {
      temp: -0.03, contrast: -0.18, rolloff: 0.5, shadows: 0.08, sat: 0.85,
      lift: [0, 0.01, 0.015],
      hsl: { green: [8, 0.8, 0.02], blue: [0, 0.9, 0] },
      grain: { amount: 0.14, size: 0.68, color: 0.3 }, halation: redHalo(0.05),
    },
  },
  {
    id: 'fuji-natura-1600', name: 'Natura 1600', brand: 'Fujifilm', iso: 1600,
    category: 'color', process: 'C-41', status: 'discontinued',
    swatch: ['#3c096c', '#ff9f1c'],
    summary: 'Cult Japan-only low-light film with surprisingly rich, natural colour.',
    traits: {
      color: 'Rich yet natural; handles ambient and mixed light with little cast, faint green bias.',
      contrast: 'Moderate.',
      grain: 'Visible but remarkably fine for ISO 1600.',
      highlights: 'Holds night-time light sources well.',
      shadows: 'Deep, slightly green-cyan.',
    },
    params: {
      temp: 0.02, tint: -0.02, contrast: 0.1, rolloff: 0.4, shadows: 0.05, sat: 1.05,
      lift: [0, 0.01, 0.01],
      hsl: { red: [0, 1.05, 0], green: [4, 1.0, 0] },
      grain: { amount: 0.55, size: 1.4, color: 0.45 }, halation: redHalo(0.1),
    },
  },
  {
    id: 'lomography-cn-800', name: 'Color Negative 800', brand: 'Lomography', iso: 800,
    category: 'color', process: 'C-41', status: 'current',
    swatch: ['#ef233c', '#2b2d42'],
    summary: 'Punchy, saturated and grainy fast film with a lo-fi edge.',
    traits: {
      color: 'Saturated, warm, strong reds and yellows.',
      contrast: 'High.',
      grain: 'Prominent.',
      highlights: 'Warm, moderately soft.',
      shadows: 'Dense with a slight magenta tinge.',
    },
    params: {
      temp: 0.06, contrast: 0.2, rolloff: 0.35, sat: 1.2,
      lift: [0.015, 0, 0.015],
      hsl: { red: [0, 1.15, 0], yellow: [0, 1.1, 0] },
      grain: { amount: 0.5, size: 1.2, color: 0.5 }, halation: redHalo(0.1),
    },
  },
  {
    id: 'agfa-vista-200', name: 'Vista 200', brand: 'Agfa', iso: 200,
    category: 'color', process: 'C-41', status: 'discontinued',
    swatch: ['#e63946', '#f1faee'],
    summary: 'Budget film loved for vivid reds and bright blue skies.',
    traits: {
      color: 'Vivid, slightly cool; strong reds, deep blues, punchy greens.',
      contrast: 'Medium-high.',
      grain: 'Fine-to-moderate.',
      highlights: 'Neutral-cool.',
      shadows: 'Dense, slight cyan bias.',
    },
    params: {
      temp: -0.02, contrast: 0.12, rolloff: 0.3, sat: 1.15,
      lift: [0, 0.005, 0.015],
      hsl: { red: [0, 1.15, 0], blue: [0, 1.1, -0.02], green: [2, 1.05, 0] },
      grain: { amount: 0.3, size: 0.8, color: 0.4 }, halation: redHalo(0.07),
    },
  },
  {
    id: 'harman-phoenix-200', name: 'Phoenix 200', brand: 'Harman', iso: 200,
    category: 'color', process: 'C-41', status: 'current',
    swatch: ['#ff7b00', '#1b1b1b'],
    summary: 'Wild new emulsion: high contrast, orange cast, heavy halation and grain.',
    traits: {
      color: 'Warm/orange bias with saturated reds; colour shifts with exposure.',
      contrast: 'High.',
      grain: 'Pronounced for ISO 200.',
      highlights: 'Strong red halation around highlights; highlights blow quickly.',
      shadows: 'Dense, warm shadows.',
    },
    params: {
      temp: 0.1, contrast: 0.33, rolloff: 0.2, sat: 1.18,
      lift: [0.02, 0.005, 0],
      hsl: { red: [0, 1.2, 0], orange: [0, 1.1, 0], blue: [4, 0.95, 0] },
      grain: { amount: 0.55, size: 0.9, color: 0.5 }, halation: { amount: 0.4, color: [1, 0.3, 0.1] },
    },
  },

  // ───────────────────────────────── B&W ─────────────────────────────────
  {
    id: 'kodak-tri-x-400', name: 'Tri-X 400', brand: 'Kodak', iso: 400,
    category: 'bw', process: 'B&W', status: 'current',
    swatch: ['#f6b917', '#111111'],
    summary: 'The photojournalism legend: gritty, contrasty, endlessly forgiving.',
    traits: {
      color: 'Panchromatic with slightly elevated blue sensitivity (skies render light).',
      contrast: 'Medium-high with deep blacks and bright mids.',
      grain: 'Classic visible cubic grain with real character.',
      highlights: 'Good latitude, moderately soft shoulder.',
      shadows: 'Deep but retain texture.',
    },
    params: {
      type: 'bw', bwMix: [0.27, 0.48, 0.25], contrast: 0.3, shadows: -0.05, rolloff: 0.35,
      grain: { amount: 0.45, size: 1, color: 0 }, halation: bwHalo(),
    },
  },
  {
    id: 'kodak-tmax-100', name: 'T-Max 100', brand: 'Kodak', iso: 100,
    category: 'bw', process: 'B&W', status: 'current',
    swatch: ['#f6b917', '#4a4e69'],
    summary: 'Tabular-grain precision: razor-sharp, clean, modern.',
    traits: {
      color: 'Panchromatic, fairly even sensitivity.',
      contrast: 'Medium-high, crisp.',
      grain: 'Extremely fine T-Grain.',
      highlights: 'Long straight-line; can block up if overdeveloped.',
      shadows: 'Clean and deep.',
    },
    params: {
      type: 'bw', bwMix: [0.3, 0.5, 0.2], contrast: 0.25, rolloff: 0.3,
      grain: { amount: 0.1, size: 0.6, color: 0 }, halation: bwHalo(0.03),
    },
  },
  {
    id: 'kodak-tmax-p3200', name: 'T-Max P3200', brand: 'Kodak', iso: 3200,
    category: 'bw', process: 'B&W', status: 'current',
    swatch: ['#f6b917', '#6a040f'],
    summary: 'Push-ready night film: heavy grain, inky blacks.',
    traits: {
      color: 'Panchromatic with extended red sensitivity.',
      contrast: 'High when pushed; punchy mids.',
      grain: 'Very heavy and gritty.',
      highlights: 'Bright, quick to bloom around lights.',
      shadows: 'Inky, crushed blacks.',
    },
    params: {
      type: 'bw', bwMix: [0.33, 0.45, 0.22], contrast: 0.35, shadows: -0.1, rolloff: 0.3,
      grain: { amount: 0.8, size: 1.6, color: 0 }, halation: bwHalo(0.06),
    },
  },
  {
    id: 'ilford-hp5-plus', name: 'HP5 Plus', brand: 'Ilford', iso: 400,
    category: 'bw', process: 'B&W', status: 'current',
    swatch: ['#111111', '#f1f1f1'],
    summary: 'Ilford workhorse: softer than Tri-X, superb push latitude.',
    traits: {
      color: 'Panchromatic, slightly blue-leaning.',
      contrast: 'Medium — gentler than Tri-X.',
      grain: 'Visible, soft-edged grain.',
      highlights: 'Smooth, generous latitude.',
      shadows: 'Open with good detail.',
    },
    params: {
      type: 'bw', bwMix: [0.28, 0.48, 0.24], contrast: 0.15, shadows: 0.05, rolloff: 0.45,
      grain: { amount: 0.45, size: 1.05, color: 0 }, halation: bwHalo(),
    },
  },
  {
    id: 'ilford-fp4-plus', name: 'FP4 Plus', brand: 'Ilford', iso: 125,
    category: 'bw', process: 'B&W', status: 'current',
    swatch: ['#111111', '#3a86ff'],
    summary: 'Classic medium-speed film: fine grain, rich tonality.',
    traits: {
      color: 'Panchromatic, natural tonal rendering.',
      contrast: 'Medium.',
      grain: 'Fine.',
      highlights: 'Long smooth scale.',
      shadows: 'Detailed, rich.',
    },
    params: {
      type: 'bw', bwMix: [0.28, 0.5, 0.22], contrast: 0.2, rolloff: 0.35,
      grain: { amount: 0.2, size: 0.7, color: 0 }, halation: bwHalo(0.03),
    },
  },
  {
    id: 'ilford-pan-f-plus', name: 'Pan F Plus', brand: 'Ilford', iso: 50,
    category: 'bw', process: 'B&W', status: 'current',
    swatch: ['#111111', '#8338ec'],
    summary: 'Slow, super-fine and high in contrast — silvery and crisp.',
    traits: {
      color: 'Panchromatic.',
      contrast: 'High.',
      grain: 'Exceptionally fine.',
      highlights: 'Brilliant, can clip if overexposed.',
      shadows: 'Deep, rich blacks.',
    },
    params: {
      type: 'bw', bwMix: [0.3, 0.52, 0.18], contrast: 0.45, shadows: -0.05, rolloff: 0.2,
      grain: { amount: 0.06, size: 0.45, color: 0 }, halation: bwHalo(0.03),
    },
  },
  {
    id: 'ilford-delta-100', name: 'Delta 100', brand: 'Ilford', iso: 100,
    category: 'bw', process: 'B&W', status: 'current',
    swatch: ['#111111', '#d00000'],
    summary: 'Core-shell crystal precision with smooth, modern tonality.',
    traits: {
      color: 'Panchromatic.',
      contrast: 'Medium.',
      grain: 'Very fine.',
      highlights: 'Clean, smooth.',
      shadows: 'Detailed.',
    },
    params: {
      type: 'bw', bwMix: [0.3, 0.5, 0.2], contrast: 0.2, rolloff: 0.35,
      grain: { amount: 0.1, size: 0.6, color: 0 }, halation: bwHalo(0.03),
    },
  },
  {
    id: 'ilford-delta-400', name: 'Delta 400', brand: 'Ilford', iso: 400,
    category: 'bw', process: 'B&W', status: 'current',
    swatch: ['#111111', '#ffbe0b'],
    summary: 'Fine-grained modern 400 with crisp detail.',
    traits: {
      color: 'Panchromatic.',
      contrast: 'Medium.',
      grain: 'Finer than HP5, tighter structure.',
      highlights: 'Smooth.',
      shadows: 'Clean.',
    },
    params: {
      type: 'bw', bwMix: [0.29, 0.5, 0.21], contrast: 0.2, rolloff: 0.4,
      grain: { amount: 0.32, size: 0.95, color: 0 }, halation: bwHalo(),
    },
  },
  {
    id: 'ilford-delta-3200', name: 'Delta 3200', brand: 'Ilford', iso: 3200,
    category: 'bw', process: 'B&W', status: 'current',
    swatch: ['#111111', '#fb5607'],
    summary: 'Low-light specialist: big, soft grain and moody blacks.',
    traits: {
      color: 'Panchromatic, extended red.',
      contrast: 'Medium; flatter than P3200.',
      grain: 'Large, softer-edged grain.',
      highlights: 'Smooth, glowing.',
      shadows: 'Deep but less crushed than P3200.',
    },
    params: {
      type: 'bw', bwMix: [0.32, 0.46, 0.22], contrast: 0.25, shadows: -0.05, rolloff: 0.4,
      grain: { amount: 0.7, size: 1.6, color: 0 }, halation: bwHalo(0.06),
    },
  },
  {
    id: 'ilford-xp2-super', name: 'XP2 Super', brand: 'Ilford', iso: 400,
    category: 'bw', process: 'C-41', status: 'current',
    swatch: ['#111111', '#ff006e'],
    summary: 'Chromogenic B&W: C-41 developed, ultra-smooth with a faint print tone.',
    traits: {
      color: 'Panchromatic dye image; prints on colour paper pick up a subtle warm/cool tone.',
      contrast: 'Low, very long tonal scale.',
      grain: 'Very fine dye clouds, smooth.',
      highlights: 'Enormous overexposure latitude.',
      shadows: 'Soft, slightly cool.',
    },
    params: {
      type: 'bw', bwMix: [0.3, 0.52, 0.18], contrast: -0.1, rolloff: 0.6, shadows: 0.05,
      splitHighlight: { hue: 40, amt: 0.05 }, splitShadow: { hue: 220, amt: 0.04 },
      grain: { amount: 0.15, size: 0.8, color: 0 }, halation: bwHalo(0.03),
    },
  },
  {
    id: 'ilford-sfx-200', name: 'SFX 200', brand: 'Ilford', iso: 200,
    category: 'bw', process: 'B&W', status: 'current',
    swatch: ['#111111', '#9d0208'],
    summary: 'Extended-red film: dark dramatic skies and glowing skin.',
    traits: {
      color: 'Extended red sensitivity to ~740 nm; with a red filter yields pseudo-infrared looks.',
      contrast: 'High.',
      grain: 'Moderate.',
      highlights: 'Skin and reds render very light.',
      shadows: 'Blue skies and water go very dark.',
    },
    params: {
      type: 'bw', bwMix: [0.75, 0.2, 0.05], contrast: 0.4, shadows: -0.1, rolloff: 0.3,
      grain: { amount: 0.42, size: 0.85, color: 0 }, halation: bwHalo(0.05),
    },
  },
  {
    id: 'fuji-acros-ii', name: 'Neopan Acros II', brand: 'Fujifilm', iso: 100,
    category: 'bw', process: 'B&W', status: 'current',
    swatch: ['#2b9348', '#111111'],
    summary: 'Ortho-panchromatic super-fine film: crisp, darker reds, smooth skies.',
    traits: {
      color: 'Orthopanchromatic: reduced red sensitivity, so reds and skin darken slightly.',
      contrast: 'Medium-high, crisp.',
      grain: 'Among the finest of any B&W film.',
      highlights: 'Clean, bright.',
      shadows: 'Rich; excellent reciprocity for long exposures.',
    },
    params: {
      type: 'bw', bwMix: [0.22, 0.56, 0.22], contrast: 0.25, rolloff: 0.35,
      grain: { amount: 0.08, size: 0.55, color: 0 }, halation: bwHalo(0.03),
    },
  },
  {
    id: 'foma-fomapan-100', name: 'Fomapan 100', brand: 'Foma', iso: 100,
    category: 'bw', process: 'B&W', status: 'current',
    swatch: ['#ffd60a', '#003566'],
    summary: 'Old-school Czech emulsion: vintage tonality, bright skies.',
    traits: {
      color: 'Panchromatic with low red / high blue sensitivity — skies render pale.',
      contrast: 'Medium-high, classic look.',
      grain: 'Moderate for ISO 100.',
      highlights: 'Bright; shoulder is short.',
      shadows: 'Drop off quickly.',
    },
    params: {
      type: 'bw', bwMix: [0.24, 0.5, 0.26], contrast: 0.35, shadows: -0.05, rolloff: 0.2,
      grain: { amount: 0.35, size: 0.65, color: 0 }, halation: bwHalo(0.05),
    },
  },

  // ───────────────────────────────── Slide ─────────────────────────────────
  {
    id: 'kodak-ektachrome-e100', name: 'Ektachrome E100', brand: 'Kodak', iso: 100,
    category: 'slide', process: 'E-6', status: 'current',
    swatch: ['#f6b917', '#0077b6'],
    summary: 'Modern Kodak slide: clean, cool-neutral, crisp.',
    traits: {
      color: 'Neutral-cool with clean whites, strong blues and moderate saturation.',
      contrast: 'High (as all slide film).',
      grain: 'Extremely fine.',
      highlights: 'Little latitude — highlights clip if overexposed.',
      shadows: 'Deep, slightly cool blacks.',
    },
    params: {
      temp: -0.05, contrast: 0.3, rolloff: 0.15, sat: 1.15, shadows: -0.05,
      lift: [0, 0, 0.01],
      hsl: { blue: [0, 1.15, -0.02], aqua: [0, 1.1, 0] },
      grain: { amount: 0.08, size: 0.6, color: 0.3 }, halation: redHalo(0.04),
    },
  },
  {
    id: 'kodak-kodachrome-64', name: 'Kodachrome 64', brand: 'Kodak', iso: 64,
    category: 'slide', process: 'K-14', status: 'discontinued',
    swatch: ['#f6b917', '#c1121f'],
    summary: 'The legend: warm reds and yellows, deep skies, rich contrast.',
    traits: {
      color: 'Warm, rich reds and yellows, deep blue skies; distinct, slightly dense colour.',
      contrast: 'High.',
      grain: 'Very fine, sharp dye image.',
      highlights: 'Firm; little overexposure latitude.',
      shadows: 'Deep and dense, warm-neutral.',
    },
    params: {
      temp: 0.05, contrast: 0.38, rolloff: 0.1, shadows: -0.1, sat: 1.15,
      hsl: { red: [3, 1.2, -0.02], yellow: [-3, 1.15, 0], orange: [0, 1.08, 0], blue: [6, 1.15, -0.08], green: [-4, 0.95, -0.02] },
      grain: { amount: 0.1, size: 0.55, color: 0.3 }, halation: redHalo(0.04),
    },
  },
  {
    id: 'fuji-velvia-50', name: 'Velvia 50', brand: 'Fujifilm', iso: 50,
    category: 'slide', process: 'E-6', status: 'current',
    swatch: ['#7b2cbf', '#2b9348'],
    summary: 'Landscape saturation king: vivid, magenta-tinged, inky blacks.',
    traits: {
      color: 'Extremely saturated; vivid greens, intense reds and blues, a magenta bias.',
      contrast: 'Very high.',
      grain: 'Ultra-fine.',
      highlights: 'Narrow latitude, bright clipping.',
      shadows: 'Deep, crushed blacks.',
    },
    params: {
      tint: 0.05, contrast: 0.45, rolloff: 0.1, shadows: -0.12, sat: 1.45,
      hsl: { red: [0, 1.2, 0], green: [0, 1.15, -0.03], blue: [0, 1.05, -0.06], magenta: [0, 1.2, 0] },
      grain: { amount: 0.06, size: 0.45, color: 0.3 }, halation: redHalo(0.04),
    },
  },
  {
    id: 'fuji-velvia-100', name: 'Velvia 100', brand: 'Fujifilm', iso: 100,
    category: 'slide', process: 'E-6', status: 'current',
    swatch: ['#7b2cbf', '#e5383b'],
    summary: 'Velvia saturation with a little more neutrality and speed.',
    traits: {
      color: 'Very saturated, slightly less magenta than Velvia 50; strong reds.',
      contrast: 'High.',
      grain: 'Ultra-fine.',
      highlights: 'Narrow latitude.',
      shadows: 'Deep.',
    },
    params: {
      tint: 0.03, contrast: 0.4, rolloff: 0.12, shadows: -0.1, sat: 1.35,
      hsl: { red: [0, 1.15, 0], green: [0, 1.1, -0.02], blue: [0, 1.1, -0.03] },
      grain: { amount: 0.07, size: 0.6, color: 0.3 }, halation: redHalo(0.04),
    },
  },
  {
    id: 'fuji-provia-100f', name: 'Provia 100F', brand: 'Fujifilm', iso: 100,
    category: 'slide', process: 'E-6', status: 'current',
    swatch: ['#0077b6', '#90e0ef'],
    summary: 'Reference slide film: accurate, neutral, moderately saturated.',
    traits: {
      color: 'Neutral and faithful with clean blues; moderate saturation.',
      contrast: 'Medium-high.',
      grain: 'Extremely fine.',
      highlights: 'Neutral, limited latitude.',
      shadows: 'Clean neutral blacks.',
    },
    params: {
      contrast: 0.3, rolloff: 0.15, shadows: -0.05, sat: 1.12,
      hsl: { blue: [0, 1.08, 0] },
      grain: { amount: 0.07, size: 0.6, color: 0.3 }, halation: redHalo(0.04),
    },
  },
  {
    id: 'fuji-astia-100f', name: 'Astia 100F', brand: 'Fujifilm', iso: 100,
    category: 'slide', process: 'E-6', status: 'discontinued',
    swatch: ['#ffafcc', '#0077b6'],
    summary: 'Soft portrait slide film: gentle contrast and natural skin.',
    traits: {
      color: 'Natural with soft, accurate skin tones and restrained saturation.',
      contrast: 'Low for a slide film.',
      grain: 'Extremely fine.',
      highlights: 'Smoother than other E-6 stocks.',
      shadows: 'Detailed.',
    },
    params: {
      contrast: 0.15, rolloff: 0.3, sat: 1.02,
      hsl: { orange: [0, 0.95, 0.02], blue: [0, 1.05, 0] },
      grain: { amount: 0.07, size: 0.6, color: 0.3 }, halation: redHalo(0.04),
    },
  },
  {
    id: 'agfa-ct-precisa-100', name: 'CT Precisa 100', brand: 'Agfa', iso: 100,
    category: 'slide', process: 'E-6', status: 'discontinued',
    swatch: ['#e63946', '#457b9d'],
    summary: 'Cool, punchy consumer slide film with strong blues and cyans.',
    traits: {
      color: 'Cool bias, saturated blues and cyans; a favourite for cross-processing.',
      contrast: 'High.',
      grain: 'Fine.',
      highlights: 'Cool, clip readily.',
      shadows: 'Deep blue-black.',
    },
    params: {
      temp: -0.08, contrast: 0.32, rolloff: 0.12, shadows: -0.05, sat: 1.2,
      lift: [0, 0, 0.015],
      hsl: { blue: [0, 1.2, 0], aqua: [0, 1.1, 0] },
      grain: { amount: 0.09, size: 0.6, color: 0.3 }, halation: redHalo(0.04),
    },
  },

  // ──────────────────────────────── Cinema ────────────────────────────────
  {
    id: 'cinestill-800t', name: 'CineStill 800T', brand: 'CineStill', iso: 800,
    category: 'cine', process: 'C-41', status: 'current',
    swatch: ['#1d3557', '#e63946'],
    summary: 'Tungsten-balanced Vision3 500T without remjet: cool cast, red halos.',
    traits: {
      color: 'Tungsten balanced — cool/teal in daylight, neutral under street lights; vivid neons.',
      contrast: 'Moderate.',
      grain: 'Visible, cinematic.',
      highlights: 'Iconic red halation glow around bright lights (no anti-halation layer).',
      shadows: 'Cool teal blacks.',
    },
    params: {
      temp: -0.18, tint: -0.02, contrast: 0.1, rolloff: 0.45, sat: 1.0,
      lift: [0, 0.02, 0.04],
      hsl: { red: [0, 1.1, 0] },
      grain: { amount: 0.45, size: 1.2, color: 0.45 }, halation: { amount: 1, color: [1, 0.18, 0.06] },
    },
  },
  {
    id: 'cinestill-50d', name: 'CineStill 50D', brand: 'CineStill', iso: 50,
    category: 'cine', process: 'C-41', status: 'current',
    swatch: ['#ffb703', '#023047'],
    summary: 'Daylight Vision3 50D: ultra-fine grain, clean colour, red halation.',
    traits: {
      color: 'Clean, slightly cool daylight colour with good saturation.',
      contrast: 'Moderate.',
      grain: 'Ultra-fine.',
      highlights: 'Wide latitude with red halation around speculars.',
      shadows: 'Clean, slightly cool.',
    },
    params: {
      temp: -0.02, contrast: 0.1, rolloff: 0.5, sat: 1.05,
      grain: { amount: 0.1, size: 0.45, color: 0.3 }, halation: { amount: 0.6, color: [1, 0.2, 0.08] },
    },
  },
  {
    id: 'kodak-vision3-50d', name: 'Vision3 50D 5203', brand: 'Kodak', iso: 50,
    category: 'cine', process: 'ECN-2', status: 'current',
    swatch: ['#f6b917', '#264653'],
    summary: 'The finest-grain motion picture negative; flat, gradable, clean.',
    traits: {
      color: 'Neutral, accurate daylight colour designed for grading.',
      contrast: 'Low (log-like negative).',
      grain: 'Extremely fine.',
      highlights: 'Huge latitude; very soft shoulder.',
      shadows: 'Open.',
    },
    params: {
      contrast: -0.1, rolloff: 0.6, sat: 0.95, shadows: 0.05,
      grain: { amount: 0.07, size: 0.45, color: 0.3 }, halation: redHalo(0.04),
    },
  },
  {
    id: 'kodak-vision3-250d', name: 'Vision3 250D 5207', brand: 'Kodak', iso: 250,
    category: 'cine', process: 'ECN-2', status: 'current',
    swatch: ['#f6b917', '#2a9d8f'],
    summary: 'Daylight cinema negative: wide latitude, natural, soft.',
    traits: {
      color: 'Natural, slightly warm skin, restrained saturation.',
      contrast: 'Low.',
      grain: 'Fine.',
      highlights: 'Extremely wide latitude; very soft shoulder.',
      shadows: 'Open, detailed.',
    },
    params: {
      temp: 0.02, contrast: -0.15, rolloff: 0.65, shadows: 0.08, sat: 0.92,
      hsl: { orange: [1, 1.02, 0.01] },
      grain: { amount: 0.18, size: 0.8, color: 0.35 }, halation: redHalo(0.08),
    },
  },
  {
    id: 'kodak-vision3-500t', name: 'Vision3 500T 5219', brand: 'Kodak', iso: 500,
    category: 'cine', process: 'ECN-2', status: 'current',
    swatch: ['#f6b917', '#3d405b'],
    summary: 'Tungsten cinema workhorse: cool in daylight, soft and filmic.',
    traits: {
      color: 'Tungsten balanced — cool blue cast in daylight; muted, cinematic palette.',
      contrast: 'Low.',
      grain: 'Moderate, filmic.',
      highlights: 'Very wide latitude.',
      shadows: 'Soft and cool.',
    },
    params: {
      temp: -0.15, contrast: -0.1, rolloff: 0.65, shadows: 0.05, sat: 0.9,
      lift: [0, 0.01, 0.025],
      grain: { amount: 0.3, size: 1.1, color: 0.4 }, halation: redHalo(0.1),
    },
  },
  {
    id: 'fuji-eterna-250d', name: 'Eterna 250D', brand: 'Fujifilm', iso: 250,
    category: 'cine', process: 'ECN-2', status: 'discontinued',
    swatch: ['#2b9348', '#ced4da'],
    summary: 'Fuji cinema stock: muted, low saturation, cyan-green poise.',
    traits: {
      color: 'Restrained saturation with cool cyan-green bias and soft skin.',
      contrast: 'Low.',
      grain: 'Fine.',
      highlights: 'Soft, wide latitude.',
      shadows: 'Slightly cyan, open.',
    },
    params: {
      tint: -0.03, contrast: -0.15, rolloff: 0.6, shadows: 0.05, sat: 0.8,
      lift: [0, 0.01, 0.015],
      hsl: { green: [6, 0.8, 0], orange: [0, 0.95, 0.01] },
      grain: { amount: 0.18, size: 0.8, color: 0.35 }, halation: redHalo(0.07),
    },
  },
  {
    id: 'kodak-double-x-5222', name: 'Double-X 5222', brand: 'Kodak', iso: 250,
    category: 'cine', process: 'B&W', status: 'current',
    swatch: ['#f6b917', '#000000'],
    summary: 'Classic B&W motion picture film (Raging Bull, Schindler’s List).',
    traits: {
      color: 'Panchromatic B&W.',
      contrast: 'Medium-high, cinematic.',
      grain: 'Pronounced, gritty.',
      highlights: 'Gentle glow.',
      shadows: 'Deep, inky.',
    },
    params: {
      type: 'bw', bwMix: [0.28, 0.5, 0.22], contrast: 0.3, shadows: -0.05, rolloff: 0.35,
      grain: { amount: 0.5, size: 0.9, color: 0 }, halation: bwHalo(0.05),
    },
  },

  // ─────────────────────────────── Specialty ───────────────────────────────
  {
    id: 'kodak-aerochrome-iii', name: 'Aerochrome III 1443', brand: 'Kodak', iso: 400,
    category: 'special', process: 'E-6', status: 'discontinued',
    swatch: ['#d00000', '#ff4d6d'],
    summary: 'Colour-infrared false colour: foliage turns red and pink.',
    traits: {
      color: 'False colour (IR→red, red→green, green→blue); chlorophyll glows red/magenta, skies stay blue.',
      contrast: 'High.',
      grain: 'Fine.',
      highlights: 'Foliage highlights pink-white.',
      shadows: 'Deep blue-black.',
    },
    params: {
      matrix: [0.1, 1.3, -0.4, 1, 0, 0, 0, 0.6, 0.4],
      contrast: 0.3, rolloff: 0.2, sat: 1.25,
      grain: { amount: 0.2, size: 0.9, color: 0.35 }, halation: redHalo(0.05),
    },
  },
  {
    id: 'lomography-lomochrome-purple', name: 'LomoChrome Purple', brand: 'Lomography', iso: 400,
    category: 'special', process: 'C-41', status: 'current',
    swatch: ['#7b2cbf', '#c77dff'],
    summary: 'Colour-shifting film: greens become purple, blues go teal.',
    traits: {
      color: 'Greens → violet/purple, blues → teal-green, yellows → pink; skin stays roughly natural.',
      contrast: 'Medium.',
      grain: 'Moderate.',
      highlights: 'Neutral whites.',
      shadows: 'Purple-blue.',
    },
    params: {
      matrix: [0.75, 0.45, -0.2, 0.3, 0.05, 0.65, -0.05, 0.75, 0.3],
      contrast: 0.12, rolloff: 0.3, sat: 1.15,
      grain: { amount: 0.38, size: 1, color: 0.45 }, halation: redHalo(0.07),
    },
  },
  {
    id: 'lomography-lomochrome-metropolis', name: 'LomoChrome Metropolis', brand: 'Lomography', iso: 400,
    category: 'special', process: 'C-41', status: 'current',
    swatch: ['#6c757d', '#ced4da'],
    summary: 'Desaturated, contrasty, bleach-bypass-like urban look.',
    traits: {
      color: 'Muted, desaturated palette; yellows and greens fade, reds and blues hold a little.',
      contrast: 'High.',
      grain: 'Moderate.',
      highlights: 'Bright, silvery.',
      shadows: 'Deep, slightly cool.',
    },
    params: {
      contrast: 0.35, rolloff: 0.25, sat: 0.45, satShadows: 0.8,
      lift: [0, 0.005, 0.015],
      hsl: { green: [0, 0.5, 0], yellow: [0, 0.6, 0], red: [0, 1.2, 0], blue: [0, 1.15, 0] },
      grain: { amount: 0.38, size: 1, color: 0.4 }, halation: redHalo(0.06),
    },
  },
  {
    id: 'lomography-redscale-xr', name: 'Redscale XR 50-200', brand: 'Lomography', iso: 100,
    category: 'special', process: 'C-41', status: 'current',
    swatch: ['#d00000', '#ff9f1c'],
    summary: 'Exposed through the base: everything rendered in red, orange and amber.',
    traits: {
      color: 'Monochrome-ish fire palette — deep red shadows through orange to yellow highlights.',
      contrast: 'Medium-high.',
      grain: 'Moderate.',
      highlights: 'Glowing yellow-orange.',
      shadows: 'Deep red-brown.',
    },
    params: {
      matrix: [0.5, 0.5, 0.05, 0.15, 0.45, 0.02, 0.02, 0.08, 0.05],
      exposure: 0.3, contrast: 0.2, rolloff: 0.35, sat: 1.05,
      grain: { amount: 0.4, size: 0.9, color: 0.4 }, halation: redHalo(0.1),
    },
  },
  {
    id: 'cross-processed-e6', name: 'Cross-processed E-6', brand: 'Generic', iso: 100,
    category: 'special', process: 'C-41', status: 'current',
    swatch: ['#80ffdb', '#ffd60a'],
    summary: 'Slide film in C-41 chemistry: wild crossovers, cyan shadows, yellow-green highlights.',
    traits: {
      color: 'Saturated, unpredictable colour crossover: blue-cyan shadows, yellow-green highlights.',
      contrast: 'Very high.',
      grain: 'Moderate.',
      highlights: 'Blown, yellow-green.',
      shadows: 'Blue-cyan.',
    },
    params: {
      contrast: 0.5, rolloff: 0.15, sat: 1.35,
      lift: [0, 0.03, 0.08], gain: [1.0, 1.05, 0.85], gamma: [0.95, 1.05, 0.95],
      grain: { amount: 0.3, size: 0.75, color: 0.45 }, halation: redHalo(0.06),
    },
  },
  {
    id: 'polaroid-600', name: '600 Color', brand: 'Polaroid', iso: 640,
    category: 'special', process: 'Instant', status: 'current',
    swatch: ['#f1faee', '#e63946'],
    summary: 'Integral instant film: faded, dreamy, warm highlights and cyan shadows.',
    traits: {
      color: 'Muted, warm-yellow highlights with cyan-teal shadows.',
      contrast: 'Low.',
      grain: 'None to speak of — dye diffusion image.',
      highlights: 'Never quite white; soft bloom.',
      shadows: 'Lifted, milky blacks.',
    },
    params: {
      contrast: -0.25, rolloff: 0.5, sat: 0.85, fade: 0.06, whitePoint: 0.92,
      lift: [0, 0.04, 0.06], gain: [1.0, 0.98, 0.88],
      bloom: 0.2,
      grain: { amount: 0.04, size: 0.6, color: 0.2 }, halation: redHalo(0.05),
    },
  },
  {
    id: 'fuji-instax-mini', name: 'Instax Mini', brand: 'Fujifilm', iso: 800,
    category: 'special', process: 'Instant', status: 'current',
    swatch: ['#ffffff', '#ff8fab'],
    summary: 'Credit-card instant film: bright, cool and contrasty.',
    traits: {
      color: 'Cool, slightly magenta-blue cast; bright saturated colours.',
      contrast: 'Medium-high; limited latitude.',
      grain: 'Minimal.',
      highlights: 'Bright, tend to blow out.',
      shadows: 'Slightly lifted, cool.',
    },
    params: {
      temp: -0.05, tint: 0.02, contrast: 0.12, rolloff: 0.2, sat: 1.08, fade: 0.03, whitePoint: 0.97,
      lift: [0, 0.01, 0.025],
      bloom: 0.1,
      grain: { amount: 0.05, size: 0.6, color: 0.2 }, halation: redHalo(0.05),
    },
  },
  {
    id: 'fuji-fp-100c', name: 'FP-100C', brand: 'Fujifilm', iso: 100,
    category: 'special', process: 'Instant', status: 'discontinued',
    swatch: ['#1d3557', '#a8dadc'],
    summary: 'Peel-apart instant: soft pastel colour with a cool, painterly feel.',
    traits: {
      color: 'Cool, slightly green-cyan, pastel yet rich; lovely muted skin.',
      contrast: 'Low-to-moderate.',
      grain: 'Very fine.',
      highlights: 'Soft, creamy, slightly off-white.',
      shadows: 'Gently lifted, blue-green.',
    },
    params: {
      temp: -0.05, tint: -0.03, contrast: -0.05, rolloff: 0.45, sat: 1.0, fade: 0.03, whitePoint: 0.97,
      lift: [0, 0.015, 0.02],
      hsl: { green: [6, 0.9, 0], blue: [-4, 0.95, 0] },
      bloom: 0.08,
      grain: { amount: 0.06, size: 0.6, color: 0.2 }, halation: redHalo(0.04),
    },
  },
];

export const DEFAULT_FILM_ID = 'kodak-portra-400';

const BY_ID = new Map(FILMS.map((f) => [f.id, f]));

export function getFilm(id) {
  return BY_ID.get(id) || FILMS[0];
}
